version: '3.8'

services:
  # Run 2 web servers as replicas
  web_app:
    build:
      context: ./Perfect_world
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    networks:
      - nsa_net

  # Install nginx as reverse proxy on port 8080
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
      - "8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx           
      - goaccess_report:/var/www/goaccess
    depends_on:
      - web_app
    networks:
      - nsa_net

# Analizatorul de trafic GoAccess
  goaccess:
    image: allinurl/goaccess
    entrypoint: /bin/sh
    command: -c "touch /srv/logs/custom_access.log && goaccess /srv/logs/custom_access.log -o /srv/report/report.html --log-format=COMBINED --real-time-html --port=7890"
    ports:
      - "7890:7890"   # Portul pentru actualizarea graficelor în timp real
    volumes:
      - nginx_logs:/srv/logs
      - goaccess_report:/srv/report
    depends_on:
      - nginx
    networks:
      - nsa_net

# Baza de date MASTER (Cea principală)
  db_master:
    image: mariadb:10.6
    command: --server-id=1 --log-bin=mysql-bin
    environment:
      MYSQL_ROOT_PASSWORD: 100504
      MYSQL_DATABASE: perfect_world_db
      MYSQL_USER: alexandra
      MYSQL_PASSWORD: 1005
    volumes:
      - db_master_data:/var/lib/mysql
    networks:
      - nsa_net

  # Baza de date SLAVE (Cea care copiază)
  db_slave:
    image: mariadb:10.6
    command: --server-id=2 --log-bin=mysql-bin
    environment:
      MYSQL_ROOT_PASSWORD: 100504
      MYSQL_DATABASE: perfect_world_db   
      MYSQL_USER: alexandra              
      MYSQL_PASSWORD: 1005
    volumes:
      - db_slave_data:/var/lib/mysql
    depends_on:
      - db_master
    networks:
      - nsa_net

  # Interfața phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOSTS: db_master, db_slave   
    depends_on:
      - db_master
      - db_slave
    networks:
      - nsa_net

  redis:
    image: redis:alpine
    networks:
      - nsa_net
  # Serverul de Mail (MailHog)
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"   
    networks:
      - nsa_net
networks:
  nsa_net:
    driver: bridge

volumes:
  db_master_data:
  db_slave_data:
  nginx_logs:          
  goaccess_report:
