events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/custom_access.log combined;
    # 1. LOAD BALANCER
    upstream aplicatie_web {
        # Docker va imparti traficul in mod egal, cand pe clona 1, cand pe clona 2
        server web_app:80; 
    }

    # 2. ACL (Listele de acces)
        geo $acces_permis {
        default        0; # 0deny pentru toata lumea
        127.0.0.1      1; # Localhost
        10.0.0.0/8     1; # Retea privată clasa A
        172.16.0.0/12  1; # Reteaua privată Docker         	
	192.168.0.0/16 1; # Rețea privată clasa C (Wi-fi-ul meu)
    }

    server {
        # Interfața HTTP (Port 80 -> 8080)
        listen 80;
        server_name perfectworld.local;

        location / {
            if ($acces_permis = 0) {
                return 403; 
            }

            proxy_pass http://aplicatie_web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        # Interfata HTTPS securizata (Port 443 -> 8443)
        listen 443 ssl;
        server_name perfectworld.local;

        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        location / {
            if ($acces_permis = 0) {
                return 403;
            }

            proxy_pass http://aplicatie_web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8082;
        server_name perfectworld.local;

        location / {
            root /var/www/goaccess;
            index report.html;
        }
    }
}