events { worker_connections 1024; }

http {
    # Definim grupul de servere web
    upstream backend_servers {
        server web_app:80; 
    }

    server {
        # Install nginx as reverse proxy on port 8080
        listen 8080;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
