events {
    worker_connections 1024;
}

http {
    upstream web_backend {
        server web_app:80;
    }

    # Server pentru HTTP normal
    server {
        listen 80;
        server_name perfectworld.local localhost;

        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Server pentru HTTPS (Securizat)
    server {
        listen 443 ssl;
        server_name perfectworld.local localhost;

        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
